// <auto-generated />
using System;
using AutoVisionX.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoVisionX.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703042447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AutoVisionX.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealCarModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassLabel")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nissan",
                            ClassLabel = "skyline_r34",
                            ColorName = "Red",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ícono japonés de alto rendimiento con diseño agresivo y gran detalle.",
                            MainImageUrl = "/images/cars/skyline-r34-main.png",
                            Name = "Nissan Skyline GT-R R34",
                            OfficialColorHex = "#D90429",
                            Rarity = "Rare",
                            RealCarModel = "Nissan Skyline GT-R (R34)",
                            Series = "HW Performance",
                            Year = 2002
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota",
                            ClassLabel = "toyota_supra",
                            ColorName = "Orange",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deportivo japonés reconocido por su motor 2JZ y silueta icónica.",
                            MainImageUrl = "/images/cars/supra-main.png",
                            Name = "Toyota Supra",
                            OfficialColorHex = "#F77F00",
                            Rarity = "Uncommon",
                            RealCarModel = "Toyota Supra (A80)",
                            Series = "HW Turbo",
                            Year = 2000
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            ClassLabel = "ford_mustang",
                            ColorName = "Blue",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Muscle car americano clásico, símbolo de potencia y diseño atemporal.",
                            MainImageUrl = "/images/cars/mustang-main.png",
                            Name = "Ford Mustang",
                            OfficialColorHex = "#1D3557",
                            Rarity = "Common",
                            RealCarModel = "Ford Mustang GT",
                            Series = "HW Muscle",
                            Year = 1998
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Lamborghini",
                            ClassLabel = "lamborghini_huracan",
                            ColorName = "Green",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Superdeportivo italiano de líneas afiladas y presencia dominante.",
                            MainImageUrl = "/images/cars/huracan-main.png",
                            Name = "Lamborghini Huracán",
                            OfficialColorHex = "#2B9348",
                            Rarity = "Super Treasure Hunt",
                            RealCarModel = "Lamborghini Huracán",
                            Series = "HW Exotics",
                            Year = 2015
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Porsche",
                            ClassLabel = "porsche_911",
                            ColorName = "Yellow",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Referencia alemana en ingeniería deportiva y diseño atemporal.",
                            MainImageUrl = "/images/cars/porsche-911-main.png",
                            Name = "Porsche 911",
                            OfficialColorHex = "#FFB703",
                            Rarity = "Rare",
                            RealCarModel = "Porsche 911 Carrera",
                            Series = "HW Speed Graphics",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("AutoVisionX.API.Models.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AngleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("AutoVisionX.API.Models.DetectionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedPrimaryColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedPrimaryColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictedLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("UploadedImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("DetectionHistories");
                });

            modelBuilder.Entity("AutoVisionX.API.Models.CarImage", b =>
                {
                    b.HasOne("AutoVisionX.API.Models.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoVisionX.API.Models.DetectionHistory", b =>
                {
                    b.HasOne("AutoVisionX.API.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoVisionX.API.Models.Car", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
